CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE users (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "GuidId" uuid NOT NULL,
    "Name" text NOT NULL,
    "Cpf" text NOT NULL,
    "AccountStatus" smallint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_users" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_users_GuidId" ON users ("GuidId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260308175305_InitialCreate', '9.0.0');

COMMIT;

